Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -31,3 +31,11 @@ jobs:
 
       - name: Upload APK as Artifact
         uses: actions/upload-artifact@v4
+   
+  - name: Check if APK exists
+  run: |
+    ls -R app/build/outputs/
+    if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
+      echo "❌ APK not found!"
+      exit 1
+    fi
